// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDScReRtsXf6yJdn03wDJQOnqm3BU04hyM',
    appId: '1:794602080875:web:7d2c8550729673c234bf2e',
    messagingSenderId: '794602080875',
    projectId: 'solarencrypt-28b1c',
    authDomain: 'solarencrypt-28b1c.firebaseapp.com',
    storageBucket: 'solarencrypt-28b1c.appspot.com',
    measurementId: 'G-8CJ99NVXBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx1Q34t8umvuMXKGslDzmW-LoVWzYGunM',
    appId: '1:794602080875:android:78a10a5bbc9cf3a834bf2e',
    messagingSenderId: '794602080875',
    projectId: 'solarencrypt-28b1c',
    storageBucket: 'solarencrypt-28b1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvAUE_nu5WhIi02foMamTLTG-9ewvWDbI',
    appId: '1:794602080875:ios:28544eea101335d834bf2e',
    messagingSenderId: '794602080875',
    projectId: 'solarencrypt-28b1c',
    storageBucket: 'solarencrypt-28b1c.appspot.com',
    iosBundleId: 'com.example.solarencrypt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvAUE_nu5WhIi02foMamTLTG-9ewvWDbI',
    appId: '1:794602080875:ios:61abfaf8a26e18e434bf2e',
    messagingSenderId: '794602080875',
    projectId: 'solarencrypt-28b1c',
    storageBucket: 'solarencrypt-28b1c.appspot.com',
    iosBundleId: 'com.example.solarencrypt.RunnerTests',
  );
}
